### ISSUE TITLE
[Feature] Show speed in KB/sec and MB/sec?

### ISSUE THREAD

**Issue by sepodele** [Vaskivskyi/ha-asusrouter#132]
### The problem

I get that the raw output shows speed in mbits but can we have sensors for kB/sec and MB/sec too so we don't have to create template sensors for this? Mbits is silly.

**Comment by Vaskivskyi** [comment]
Hey, @sepodele,

`Mb/s` (`Mbits/s`) is a standard way to describe network speeds - that is why this is a default way to show them in the integration. Each entity also has a `raw` attribute in `b/s` for easy calculations of custom values.

I could think of an option in the integration configuration "Select units for XXX sensor". This one you will be able to select during the initial configuration or via the `Configure` button for the integration at any time. Of course, in the last case, the user will need to manually clean up history, otherwise, long-term statistics will complain about unit change.

If nothing else is selected, the default as it is now will be kept. In this case, most of the users will never see the change, but those who want will get custom units.

Would this be a valid option for you?

I don't like the idea of just changing units, as they are standard for such kinds of data. Also just adding more attributes in different units will create lots of mess and waste of database storage.

**Comment by sepodele** [comment]
Sure. That's certainly a valid option. 👍

**Comment by tismofied** [comment]
> ### The problem
> I get that the raw output shows speed in mbits but can we have sensors for kB/sec and MB/sec too so we don't have to create template sensors for this? Mbits is silly.
> 
> ### Specific device(s)?
> _No response_
> 
> ### Firmware type
> _No response
I would love the option to choose  output speed values. 
while we wait for an enhancment, how does one create a sensor template to show speeds in mbits?

**Comment by Vaskivskyi** [comment]
@tismofied,

I am not really getting your question, since speeds are already in `Mbits/s`. But in general, here is an answer for templates.

If you want to have a sensor in some custom units, in your configuration.yaml you need to add:

```YAML
template:
  - sensor:
      - name: Speed in kbits/s
        unique_id: speed_in_kbits_s
        state: >
          {% if not(is_state("sensor.rt_ax88u_wan_upload_speed", "unavailable")) %}
            {{ (state_attr("sensor.rt_ax88u_wan_upload_speed", "bits/s") / 1024) | round(3) }}
          {% endif %}
```

Where:
- `name` - is the name of the new sensor
- `unique_id` - needed, so you will be able to change the id from the HA frontend
- `state` - the value for the sensor.

Obviously, you should put your sensor id in there.

The most precise calculation will be from the raw units - `bits/s`- an attribute to the sensor itself.
If you want to calculate something, you should make sure that the operation can be performed (that is why there is a check for "unavailable" - otherwise you will be getting errors in the log when this happens).
`1024` is just to convert `bits/s -> kbits/s`, but you can use any factor.

If you want to convert from `bits/s` to `bytes/s`, divide by `8`.
