### ISSUE TITLE
[Bug] firmware_update.available doesn't reset to null

### ISSUE THREAD

**Issue by gmariotti** [Vaskivskyi/ha-asusrouter#375]
### The problem

Apologies in advance if this is not a bug. Before the update to `3.0.0.4.388.1_0` became available for my router, the value in the `available` property was set to `null`. It changed as expected when the update became available but now, after the router is updated, the value is still stuck on that version. Is this the expected behavior?

For reference, this is how the current state looks like for the entity

```yaml
auto_update: false
installed_version: 3.0.0.4.388.1_0
in_progress: false
latest_version: 3.0.0.4.388.1_0
release_summary: null
release_url: null
skipped_version: null
title: null
current: 3.0.0.4.388.1_0
available: 3.0.0.4.388.1_0
entity_picture: https://brands.home-assistant.io/_/asusrouter/icon.png
icon: mdi:update
friendly_name: RT-AX58U Firmware update
supported_features: 0
```

### Your device model

RT-AX58U

### Firmware type

Merlin

### Firmware version

3.0.0.4.388.1_0

### Integration version with the issue

0.14.3

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2022.12.6
