### ISSUE TITLE
[Device support] Upload/Download values seem to be monthly stats

### ISSUE THREAD

**Issue by 1PlusN** [Vaskivskyi/ha-asusrouter#577]
### Anything you want to mention?

Have a feeling this is due to how the device is reporting the stat, but I am trying to get the daily downloads / upload values out of the "rt_ax95q_wan_download(upload)" sensor. The values reported seem to be monthly, but the daily stats are available on the router itself. 

So far this seems to be a PEBKAC issue, and not one with the integration itself. 

from the HA side, I cannot seem to find a way to reset this value daily outside of the meters sensor, which this is not. 

thoughts or input would be appreciated. 

### Your device model

ZenWifi AX (XT8)

### Firmware type

Stock

### Firmware version

3.0.0.4.388_22525

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hello, @1PlusN,

Thanks for your feedback.

The sensors are actually cumulative for the traffic of the router and do not depend on the time period. They might reset only on reboot (or older model when the value overflows some limit)

If you want daily/weekly/monthly usage properly, I suggest creating a `utility meter` in HA, binding it to the sensor from the integration.

Here is an example of YAML for daily and monthly sensors:

```YAML
utility_meter:
  router_upload_monthly:
    source: sensor.router_wan_upload
    cycle: monthly
    name: Router/Upload/Monthly
  router_download_daily:
    source: sensor.router_wan_download
    cycle: daily
    name: Router/Download/Daily
```
