### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Fettkeewl** [Vaskivskyi/ha-asusrouter#744]
### The problem

Add sensor for which WAN is used
I wan't to know when router switches from primary WAN to secondary (USB 4g) WAN because primary has dropped connection.
I'm currently tracking this with a curl request to ipinfo but would be better if I could get the info from my router

### Specific device(s)?

None

### Firmware type

None

**Comment by Vaskivskyi** [comment]
Hello,

You can already use the `binary_sensor.{device}_internet` sensor. Except for the value showing whether your router has a connection to the internet, it has an attribute `wan_unit` corresponding to the currently used connection.

If your dual wan setup has WAN as the main and USB as the secondary connection the value would be:

- `0` for when WAN is used
- `1` for when USB is used

A simple template would be:

```
{{ is_state_attr("binary_sensor.{device}_internet", "wan_unit", 0) }}
```

To return `true` when unit `0` is used and `false` when unit `1`

You can automate it in HA like this:

```yaml
description: Internet unit changed automation
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.{device}_internet
    attribute: wan_unit
    from: 0
    to: 1
condition: []
action: []
```

Please, note that the value of the attribute is an integer number. So, you cannot compare it to a string `"0"` or `"1"`, but only to a number `0` or `1`
